# Generated by Django 3.2 on 2021-04-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='your Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Your Email')),
                ('zip_code', models.CharField(max_length=30, verbose_name='Your Zip Code')),
                ('phone', models.CharField(max_length=30, verbose_name='Your Phone')),
                ('website', models.URLField(verbose_name='Website Link')),
            ],
        ),
    ]
