# Generated by Django 3.2 on 2021-04-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_index', '0002_task_expert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='expert',
        ),
    ]
